CREATE DATABASE IF NOT EXISTS MULTIMODAL_ANALYSIS;
CREATE SCHEMA IF NOT EXISTS MULTIMODAL_ANALYSIS.MEDIA;

-- Create image storage stage
CREATE STAGE IF NOT EXISTS MULTIMODAL_ANALYSIS.MEDIA.IMAGES
  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')
  DIRECTORY = (ENABLE = true);

-- Create audio storage stage  
CREATE STAGE IF NOT EXISTS MULTIMODAL_ANALYSIS.MEDIA.AUDIO
  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')
  DIRECTORY = (ENABLE = true);